{{- if eq .Values.environment "prod" }}
---
# Source: redis-cluster/templates/headless-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-headless
  namespace: {{ .Values.namespace }}
  labels:
    k8s-app: redis-cluster
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: tcp-redis
      port: 6379
      targetPort: tcp-redis
    - name: tcp-redis-bus
      port: 16379
      targetPort: tcp-redis-bus
  selector:
    k8s-app: redis-cluster
---
# Source: redis-cluster/templates/redis-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: redis-cluster
  namespace: {{ .Values.namespace }}
  labels:
    k8s-app: redis-cluster
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: tcp-redis
      port: 6379
      targetPort: tcp-redis
      protocol: TCP
  selector:
    k8s-app: redis-cluster
{{- end }}