---
# Testing temporal secret - don't use on prod
# Source: redis-cluster/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: redis-cluster-secret
  namespace: {{ .Values.namespace }}
  labels:
    k8s-app: redis-cluster
type: Opaque
data:
  redis-password: "b3JtTlM4cTdRNQ=="