# ---
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   namespace: {{ .Values.namespace}}
#   name: example-secret-sync
# spec:
#   refreshInterval: 1m
#   secretStoreRef:
#     kind: ClusterSecretStore
#     name: azure-store
#   target:
#     name: {{/* .Values.example.kubernetes.secret.name */}}
#   dataFrom:
#   - extract:
#       key: {{/* .Values.example.vault.secret.name */}} 