registry:
  url: alejandroreba
# imagePullSecretKey: ''

environment: dev
namespace: sre-challenge

visitTrackerApp:
  nodeSelector: { agentpool: visitTrackerApp } # example of nodeSelector matching a nodeLabel
  tolerations:
    [
      {
        effect: "NoSchedule",
        key: dedicated,
        operator: Equal,
        value: visitTrackerApp
      },
      {
        effect: "NoSchedule",
        key: dedicated,
        operator: Equal,
        value: defaultWorkload
      }
    ]
  antiAffinity: soft

redisDB:
  resources:
    limits:
      cpu: 250m
      ram: 256Mi
    requests:
      cpu: 250m
      ram: 256Mi
  antiAffinity: soft
  storage: "5Gi"