name: ci-build-publish

on:
  push:
    branches: [ "main-challenge" ]

jobs:
  build:
    name: ci-build-publish
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        target: runner
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/visit-tracker-app:${{ github.sha }}, ${{ secrets.DOCKERHUB_USERNAME }}/visit-tracker-app:latest
        secrets: |
          "github_token=${{ secrets.GITHUB_TOKEN }}"
